name: Deploy Staging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY_STAGE}}
          heroku_app_name: ${{secrets.HEROKU_API_APP_STAGE}}